appli:
  name: frontend-helm
  replicas: 1
  image:
    owner: amauryfaveriel
    name: t-clo-902-front
    version: "1.1"

env:
  api_url: 35.189.222.226

service:
  type: LoadBalancer

ports:
  applicationPort: "80"

configmap:
  name: frontend-helm-configmap