apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.rabbitmq.appli.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.rabbitmq.appli.name}}
      project: {{ .Values.global.project.name }}
      stage: {{ .Values.global.project.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.global.rabbitmq.appli.name }}
        project: {{ .Values.global.project.name }}
        stage: {{ .Values.global.project.stage }}
    spec:
      containers:
      - image: {{ .Values.global.rabbitmq.image.name}}:{{ .Values.global.rabbitmq.image.version }}
        name: {{ .Values.global.rabbitmq.appli.name}}
        env:
        {{- range .Values.global.rabbitmq.appli.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.global.rabbitmq.ports.applicationPort }}
        volumeMounts:
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-conf
          configMap:
            name: rabbitmq-helm-configmap
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf