apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appli.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appli.name }}
      project: {{ .Values.global.project.name }}
      stage: {{ .Values.global.project.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appli.name }}
        project: {{ .Values.global.project.name }}
        stage: {{ .Values.global.project.stage }}
    spec:
      containers:
      - image: {{ .Values.appli.image.name }}:{{ .Values.appli.image.version }}
        name: {{ .Values.appli.name}}
        ports:
        - containerPort: {{ .Values.ports.applicationPort }}
        volumeMounts:
            - name: rabbitmq-conf
              mountPath: /etc/rabbitmq/rabbitmq.conf
              subPath: rabbitmq.conf
      volumes:
        - name: rabbitmq-conf
          secret:
            secretName: {{ .Values.secret.name }}
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf