apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
type: Opaque
stringData:
  rabbitmq.conf: |
    default_vhost = {{ .Values.global.rabbitmq.appli.credentials.vhost }}
    default_user = {{ .Values.global.rabbitmq.appli.credentials.user }}
    default_pass = {{ .Values.global.rabbitmq.appli.credentials.password }}
    