apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tc2-mysql-pvc
  labels:
    app: mysql
    project: t-clo-902
    stage: recette
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 2Gi