apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: svc-mysql
    project: t-clo-902
    stage: recette
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql