apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.appli.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
data:
  discovery.type: single-node
  xpack.security.enabled: "false"