apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appli.name}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appli.name}}
      project: {{ .Values.global.project.name }}
      stage: {{ .Values.global.project.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appli.name }}
        project: {{ .Values.global.project.name }}
        stage: {{ .Values.global.project.stage }}
    spec:
      containers:
      - image: {{ .Values.appli.image.name}}:{{ .Values.appli.image.version }}
        name: {{ .Values.appli.name}}
        env:
        {{- range .Values.global.elasticsearch.appli.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end}}
        ports:
        - containerPort: {{ .Values.ports.API.applicationPort }}
        - containerPort: {{ .Values.ports.binary.applicationPort }}
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /var/lib/elasticsearch
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}