apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.appli.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
type: Opaque
stringData:
  ELASTIC_PASSWORD: {{ .Values.global.elasticsearch.appli.credentials.password }}