apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.elasticsearch.service.name }}
  labels:
    app: {{ .Values.global.elasticsearch.service.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: api
    port: {{ .Values.global.elasticsearch.ports.API.enterPort }}
    targetPort: {{ .Values.ports.API.applicationPort }}
  - name: binary
    port: {{ .Values.global.elasticsearch.ports.binary.enterPort }}
    targetPort: {{ .Values.ports.binary.applicationPort }}
  selector:
    app: {{ .Values.appli.name }}