apiVersion: v1
kind: Service
metadata:
  name: svc-backend
  labels:
    app: svc-backend
    project: t-clo-902
    stage: recette
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: backend