apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appli.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appli.name }}
      project: {{ .Values.global.project.name }}
      stage: {{ .Values.global.project.stage }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.appli.name }}
        project: {{ .Values.global.project.name }}
        stage: {{ .Values.global.project.stage }}
    spec:
      containers:
      - image: {{ .Values.appli.image.name }}:{{ .Values.appli.image.version }}
        name: {{ .Values.appli.name }}
        envFrom:
        - secretRef:
            name: {{ .Values.secret.name }}
        ports:
        - containerPort: {{ .Values.ports.applicationPort }}
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}