apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.appli.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
data:
  DB_HOST: {{ .Values.global.mysql.service.name }}
  DB_PORT: "{{ .Values.global.mysql.ports.enterPort }}"
  DB_DATABASE: {{ .Values.global.mysql.appli.credentials.dbname }}
  DB_USERNAME: {{ .Values.global.mysql.appli.credentials.user }}
  DB_PASSWORD: {{ .Values.global.mysql.appli.credentials.password }}
  ELASTICSEARCH_HOST: {{ .Values.global.elasticsearch.service.name }}
  ELASTICSEARCH_SCHEME: http
  RABBITMQ_HOST: {{ .Values.global.rabbitmq.service.name }}
  RABBITMQ_PORT: "{{ .Values.global.rabbitmq.ports.enterPort }}"
  RABBITMQ_USER: {{ .Values.global.rabbitmq.appli.credentials.user }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.appli.credentials.password }}
  RABBITMQ_VHOST: {{ .Values.global.rabbitmq.appli.credentials.vhost }}