apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.appli.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
data:
  DB_HOST: {{ .Values.global.mysql.service.name }}
  DB_PORT: "{{ .Values.global.mysql.ports.enterPort }}"
  ELASTICSEARCH_HOST: {{ .Values.global.elasticsearch.service.name }}
  RABBITMQ_HOST: {{ .Values.global.rabbitmq.service.name }}
  RABBITMQ_PORT: "{{ .Values.global.rabbitmq.ports.enterPort }}"