apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appli.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appli.name }}
      project: {{ .Values.global.project.name }}
      stage: {{ .Values.global.project.stage }}
  replicas: {{ .Values.appli.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appli.name }}
        project: {{ .Values.global.project.name }}
        stage: {{ .Values.global.project.stage }}
    spec:
      containers:
      - name: {{ .Values.appli.name }}
        image: {{ .Values.appli.image.owner }}/{{ .Values.appli.image.name }}:{{ .Values.appli.image.version }}
        imagePullPolicy: Always
        workingDir: /var/www/html
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        - secretRef:
            name: {{ .Values.secret.name }}
        ports:
        - containerPort: {{ .Values.ports.applicationPort }}
      initContainers:
      - name: database-migrate
        image: {{ .Values.appli.image.owner }}/{{ .Values.appli.image.name }}:{{ .Values.appli.image.version }}
        workingDir: /var/www/html
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
        - secretRef:
            name: {{ .Values.secret.name }}
        command:
          - php
        args:
          - artisan
          - migrate
          - --force
