apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
type: Opaque
stringData:
  DB_DATABASE: {{ .Values.global.mysql.appli.credentials.dbname }}
  DB_USERNAME: {{ .Values.global.mysql.appli.credentials.user }}
  DB_PASSWORD: {{ .Values.global.mysql.appli.credentials.password }}
  ELASTICSEARCH_SCHEME: http
  ELASTICSEARCH_USER: elastic
  ELASTICSEARCH_PASS: {{ .Values.global.elasticsearch.appli.credentials.password }}
  RABBITMQ_USER: {{ .Values.global.rabbitmq.appli.credentials.user }}
  RABBITMQ_PASSWORD: {{ .Values.global.rabbitmq.appli.credentials.password }}
  RABBITMQ_VHOST: {{ .Values.global.rabbitmq.appli.credentials.vhost }}