apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    app: {{ .Values.appli.name }}
    project: {{ .Values.global.project.name }}
    stage: {{ .Values.global.project.stage }}
type: Opaque
stringData:
  AMQP_URI: "amqp://{{ .Values.global.rabbitmq.appli.credentials.user }}:{{ .Values.global.rabbitmq.appli.credentials.password }}@{{ .Values.global.rabbitmq.service.name }}:{{ .Values.global.rabbitmq.ports.enterPort }}"
  ELASTICSEARCH_URI: "http://{{ .Values.global.elasticsearch.service.name }}:{{ .Values.global.elasticsearch.ports.API.enterPort }}"