appli:
  name: elasticsearch-helm
  image:
    name: elasticsearch
    version: 8.1.3

service:
  type: ClusterIP

ports:
  API:
    applicationPort: 9200
  binary:
    applicationPort: 9300

pvc:
  name: tc2-elasticsearch-pvc-helm