appli:
  name: backend-helm
  replicas: 2
  image:
    owner: amauryfaveriel
    name: t-clo-902-back
    version: "1.1"

service:
  type: ClusterIP

ports:
  applicationPort: "80"

configmap:
  name: backend-helm-configmap