global:
  project:
    name: t-clo-902
    stage: recette
  backend:
    service:
      name: svc-backend-helm
    ports:
      enterPort: "80"
  mysql:
    appli:
      credentials:
        user: tc2-user
        password: tc2-password
        dbname: tc2-database
      env:
        - name: MYSQL_USER
          value: tc2-user
        - name: MYSQL_PASSWORD
          value: tc2-password
        - name: MYSQL_DATABASE
          value: tc2-database
    ports:
      enterPort: "3306"
    service:
      name: svc-mysql-helm
  frontend:
    appli:
      env:
        - name: API_URL
          value: http://localhost:8080/api
    ports:
      enterPort: "80"
    service:
      name: svc-frontend-helm
  elasticsearch:
    appli:
      env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "'false'"
    service:
      name: svc-elasticsearch-helm
    ports:
      API:
        enterPort: 9200
      binary:
        enterPort: 9300
  rabbitmq:
    appli:
      credentials:
        user: guest
        password: guest
        vhost: /
    service:
      name: svc-rabbitmq-helm
    ports:
      enterPort: "5672"
  indexer:
    appli:
      env:
        - name: AMQP_URI
          value: amqp://guest:guest@svc-rabbitmq-helm:5672
        - name: ELASTICSEARCH_URI
          value: http://svc-elasticsearch-helm:9200
      
