global:
  project:
    name: t-clo-902
    stage: recette
  backend:
    service:
      name: svc-backend-helm
    ports:
      enterPort: "80"
  mysql:
    appli:
      credentials:
        user: tc2-user
        password: tc2-password
        dbname: tc2-database
    ports:
      enterPort: "3306"
    service:
      name: svc-mysql-helm
  frontend:
    ports:
      enterPort: "80"
    service:
      name: svc-frontend-helm
  elasticsearch:
    appli:
      credentials:
        password: elasticsearch-pass
    service:
      name: svc-elasticsearch-helm
    ports:
      API:
        enterPort: 9200
      binary:
        enterPort: 9300
  rabbitmq:
    appli:
      credentials:
        user: rabbitmq-user
        password: rabbitmq-pass
        vhost: /
    service:
      name: svc-rabbitmq-helm
    ports:
      enterPort: "5672"
      
